[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# Compiler settings
solc_version = "0.8.26"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Fuzz testing
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# RPC endpoints
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
local = "http://localhost:8545"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Gas price settings
[profile.sepolia]
gas_price = 20_000_000_000  # 20 gwei

[profile.mainnet]
gas_price = 30_000_000_000  # 30 gwei